name: Login to Remote Server
'on':
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install SSH
        run: sudo apt-get install -y ssh
      - name: Log in to server
        uses: Bidyanda/mygitactions@master
        with:
          host: '143.110.240.100'
          username: 'root'
          password: 'gLobizs@123s'
          port: '22'
          script: |
            echo "Logged in to server"
