name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: SSH and Deploy
        uses: ./.github/actions/test
        with:
          host: 143.110.240.100
          username: ${{ secrets.USERNAME }}
          port: 22
          script: |
            echo "Logged in to server"
